# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e98fdbd895117e1893650d4c382a42b143be5208a5400f311ccde0d55a120ce84ef44b63a988b8fed9de20f8229307d37f966a764eb3adf0d521b8baf56b173

test:
  secret_key_base: e46bace5b92fec436ff39c58bf5e6e0beb3dff6b6d4e029473bd35815d160e47842c98c86398fa00e2518c6c036a128931b1bfe5f9555e635f2ee114236d4127

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
